### ISSUE TITLE
No ack for postMessage initChild()

### ISSUE THREAD

**Issue by zomaish** [krakenjs/zoid#317] opened 2020-07-24 14:47 UTC
I am using Zoid to load an external page in an iFrame in my application. My host page is a bit heavy with content (nothing I can do about the page DOM nodes or content immediately). When I load the parent page, my child content doesn't appear  in the zoid iFrame and I get the following error No ack for postMessage initChild() in (domain here) in 10000ms.

Useful information:
Zoid: 9.0.42, also tried updating to 9.0.47
Zoid React driver 
import from zoid.frameworks
React: 16.x
Browser: Chrome
some callbacks are passed into zoid props

I can reproduce the issue on a page that has few DOM nodes, all I need to do is add a big blocking loop in any of my render functions

const ComponentThatHasNothingToDoWithZoid = () => {
   for (i=0; i< 200000000; i++)
}

I looked into the zoid code a bit and it seems that when the browser is busy doing work on the main thread (I might be wrong here) it is exceeding the 10000ms max wait time to ack the response
Is there a way to either increase the ackTimeout? or is the problem elsewhere?

Thank you for your help

**Comment by zomaish** [comment] 2020-07-27 15:58
Any advice on this issue?

**Comment by gregjopa** [comment] 2020-07-27 17:03
Hi @zomaish can you try increasing the timeout with this approach?
```js
zoid.postRobot.CONFIG.ACK_TIMEOUT = 5000;
```

https://github.com/krakenjs/zoid/issues/207#issuecomment-460873784

**Comment by zomaish** [comment] 2020-07-27 17:23
@gregjopa I have tried this config from https://github.com/krakenjs/zoid/issues/207#issuecomment-460873784 but got this error
Uncaught TypeError: Cannot read property 'CONFIG' of undefined

Is there a configuration I need to add to expose postrobot. When I console.log(zoid) I get this prototype
CONTEXT: (...)
EVENT: (...)
PROP_SERIALIZATION: (...)
PROP_TYPE: (...)
PopupOpenError: (...)
create: (...)
destroy: (...)
destroyAll:(...)
destroyComponents: (...)

**Comment by zomaish** [comment] 2020-07-27 20:53
@bluepnume any ideas/suggestions?

**Comment by gregjopa** [comment] 2020-07-27 20:54
@zomaish Ahh good point. That solution (`zoid.postRobot.CONFIG.ACK_TIMEOUT`) seems out-of-date. Sorry about that.

It looks like there is a `timeout` option with zoid: https://github.com/krakenjs/zoid/blob/9d99ab78697428feaea6f6e3358deeff2d441da3/src/component/props.js#L35. Can you try passing it when you render the component? Here's an example:

```js
// render the zoid component
MyLoginZoidComponent({
    timeout: 100,  // set the timeout to 100 ms to force a timeout error
    prefilledEmail: 'foo@bar.com',
```

<img width="859" alt="Screen Shot 2020-07-27 at 3 51 31 PM" src="https://user-images.githubusercontent.com/534034/88590977-3af73880-d021-11ea-88ef-e5802c4583e7.png">

**Comment by zomaish** [comment] 2020-07-28 12:08
@gregjopa thank you for responding. This timeout prop has to do with component rendering and seems to be a bit different than the error that I'm getting. The error that I am getting is related to this code https://github.com/krakenjs/zoid/blob/master/dist/zoid.frameworks.js#L2632 which is hardcoding the timeout.
I think ultimately zoid.postRobot.CONFIG.ACK_TIMEOUT = 5000; is what I want, but it doesn't seem to be allowed anymore or it was enabled in v6.

**Comment by anthonykhoa** [comment] 2020-10-09 18:29
@mstuart please assign me! :)

**Comment by anthonykhoa** [comment] 2020-10-09 18:41
@mstuart please assign me :)

**Comment by mnicpt** [comment] 2020-10-09 18:42
@anthonykhoa Enjoy!

**Comment by anthonykhoa** [comment] 2020-10-10 19:40
@mstuart @mnicpt I think this issue may have already been resolved. I have tried reproducing the error [here](http://zoid-demo.khoa.app/) but could not. In several places in the front-end code, I have this big blocking loop:
```
for (let i = 0; i < 200000000; i++) {
        console.log('hi')
      }
```
This big loop runs after someone clicks on the `startZoidDemo` button. I do not see any errors being logged, and have checked in browsers `Google Chrome` and `Mozilla firefox`.

In firefox, this message displays at the top.
<img width="483" alt="Screen Shot 2020-10-10 at 10 04 44 AM" src="https://user-images.githubusercontent.com/45890848/95663632-b2534900-0af5-11eb-899b-b66f39d13157.png">

**Comment by anthonykhoa** [comment] 2020-10-10 20:08
@mstuart @mnicpt I think this issue may have already been resolved. I have tried reproducing the error [here](http://zoid-demo.khoa.app/) but could not. In the child window, I have this big blocking loop:
```
for (let i = 0; i < 2000000; i++) {
        console.log('hi')
      }
```
The child window appears after someone clicks on the `startZoidDemo. I do not see any errors being logged, and have checked in browsers `Google Chrome` and `Mozilla firefox`. After the loop finishes running, all the contents in the child window appears.

In firefox, this message displays at the top.
<img width="483" alt="Screen Shot 2020-10-10 at 10 04 44 AM" src="https://user-images.githubusercontent.com/45890848/95663632-b2534900-0af5-11eb-899b-b66f39d13157.png">

**Comment by mnicpt** [comment] 2020-10-12 20:43
Thanks, @anthonykhoa !  Appreciate all of your help!

**Closed by mnicpt** 2020-10-12 20:43 UTC
Labels: hacktoberfest, 🎃 Hacktoberfest

**Comment by mstuart** [comment] 2020-10-21 04:23
Thanks @anthonykhoa ! :D

**Comment by fryck** [comment] 2021-05-10 15:41
@anthonykhoa 

> I think this issue may have already been resolved

It seems not fixed, I got this error reported in our sentry (a lot) but I'm not able to reproduce it on my development environment (latest version of zoid) what can cause this issue ? I'm really confused.

**Comment by ashwin-nath-m** [comment] 2022-12-07 03:43
@fryck Did u find a solution for this? Same here, lot of errors in sentry but none in dev.
