### ISSUE TITLE
Disabling prerenderTemplate stops rendering main component

### ISSUE THREAD

**Issue by r0stig** [krakenjs/zoid#264] opened 2019-09-03 07:59 UTC
This is a continuation of this issue: https://github.com/krakenjs/zoid/issues/202#issuecomment-527210892
This might just be a feature request, it's up to you to decide :-) .

Before in version 7.x I was able to set prerenderTemplate to null to disable the loading spinner. But in 9.x I have to include the prerenderTemplate in the DOM within the containerTemplate or the main component won't show. This is actually stated in the docs (https://github.com/krakenjs/zoid/blob/master/docs/api.md#containertemplate-opts--htmlelement) but it's still something that changed and it's weird (?) to have to include it when you're not using it.

I created a gist to show the problem: https://gist.github.com/r0stig/7f59c8abcef81f5a434d2e2dd8c56703
I removed some code from our main project which is why is looks like there are many unnecessary container/wrappers.

It would be nice with a option where you won't render the prerenderTemplate at all.

**Comment by anthonykhoa** [comment] 2020-10-15 04:13
Hi @mstuart @bluepnume @mnicpt I have taken a look at this issue. 
[Click here](https://prerender-error.khoa.app/normal/zoid.html) to see a reproduction of the issue

After experimenting/digging around in the codebase, I have come to a hypothesis that the `prerenderFrame` is used for security-check purposes. Without the `prerenderFrame`, the security checks won't pass, and thus the iFrames will render no content unless the `prerenderFrame` is attached to the container. 

Can someone confirm if my hypothesis is true?

Also, I have found how to make it such that the `prerenderFrame` does not appear by using the `prerenderTemplate`. If the `prerenderFrame` is used for security purposes, then I think this issue should be closed since the below code already offers a convenient way to not display the `prerenderFrame`.

 [Click here](https://prerender-error.khoa.app/fixed/zoid.html) to see an example of using the below code
```
const ZoidDemo = zoid.create({
  tag: 'my-login-component',
  url: '/fixed/zoid2.html',
  dimensions: {
    width: '500px',
    height: '600px',
  },
  containerTemplate: function containerTemplate({
    doc,
    uid,
    frame,
    prerenderFrame,
  }) {
    const container = doc.createElement('div')
    container.id = uid
    container.appendChild(frame)
    container.appendChild(prerenderFrame)
    zoid1.append(container)
    return container
  },
  prerenderTemplate: function () {
    return null
  },
})
```

**Comment by bluepnume** [comment] 2020-10-15 04:24
Hi,

The prerender template has very little to do with security - it's just to synchronously render some content (e.g. a loading spinner) while the main iframe loads.

I tested with `prerenderTemplate: null` and `prerenderTemplate: () => null` just now, and both seem to work for me. That has the effect of suppressing the loading spinner that zoid adds by default.

Seems like the issue from the original report may be fixed already? Unless you're seeing a different issue.

**Comment by anthonykhoa** [comment] 2020-10-15 04:28
Yes @bluepnume, it seems that the original report has been fixed already.

**Comment by bluepnume** [comment] 2020-10-15 04:35
Aha! I missed your note saying "then I think this issue should be closed". Will close it now, thanks again!

**Closed by bluepnume** 2020-10-15 04:35 UTC

**Comment by anthonykhoa** [comment] 2020-10-15 18:47
@bluepnume question: `container.appendChild(prerenderFrame)` <-- why is this line necessary? why does it have to be done in addition to `container.appendChild(frame)`? My digging has led me to this file:
https://github.com/krakenjs/zoid/blob/master/src/parent/parent.js#L756

That seems to be a file where lots of magic involving the `prerenderFrame` and `frame` is done

```
const ZoidDemo = zoid.create({
  tag: 'my-login-component',
  url: '/fixed/zoid2.html',
  dimensions: {
    width: '500px',
    height: '600px',
  },
  containerTemplate: function containerTemplate({
    doc,
    uid,
    frame,
    prerenderFrame,
  }) {
    const container = doc.createElement('div')
    container.id = uid
    container.appendChild(frame)
    container.appendChild(prerenderFrame) // <----------- why is this necessary?
    zoid1.append(container)
    return container
  },
  prerenderTemplate: function () {
    return null
  },
})
```

**Comment by mnicpt** [comment] 2020-10-15 20:15
Hey, @anthonykhoa! @bluepnume is taking some time off for the next two weeks for some much deserved down time.  I can help you though.  I’ll take a look at this in the morning and hopefully be able to answer your question.  Really appreciate all of your help!

**Comment by anthonykhoa** [comment] 2020-10-15 23:18
Awesome! I appreciate the help @mnicpt!

**Comment by r0stig** [comment] 2020-11-10 08:05
To clarify: this issue asks the same question as @anthonykhoa, I came up with the same workaround as you but the question is why the prerenderFrame has to be included in the DOM when it's not used. I just tested with the latest version and the issue is the same.
